vocdoni/saas-backend

api/api.go, api/auth.go, api/docs.md, api/errors_definition.go, api/routes.go, api/transaction.go, api/types.go, db/const.go, db/types.go, db/users.go, db/users_test.go
* Create a relation between roles and write access to be able to filter user organizations based on that
* New endpoint to get the current user writable organization addresses
* Update and fix API docs.
=> feature: writable organizations endpoint

api/auth.go
=> Updates refreshTokenHalder to use the corectly the context instead of HTTP header

.github/workflows/main.yml, account/account.go, api/api.go, api/api_test.go, api/routes.go, api/users_test.go, db/mongo.go, go.mod, test/mongodb.go, test/voconed.go
* Testing API setup includes Voconed, Vocdoni Faucet, MongoDB and API service.
* MongoDB instance is globally available to be accessed directly in unit tests.
* Initial register endpoint tests done.
=> feature: api tests setup

api/organizations.go, api/types.go, db/types.go
org attributes updated in db and api layer
=> feature: new organizations attributes

api/api.go, api/docs.md, api/organizations.go, api/routes.go, api/types.go, db/const.go
Check the updated [API docs](https://github.com/vocdoni/saas-backend/blob/f/org_and_member_types_endpoint/api/docs.md#-available-organization-members-roles)
=> feature: new endpoints to get organization types and available member roles

api/api.go, api/docs.md, api/organizations.go, api/routes.go, api/types.go, db/organization_invites.go, db/organization_invites_test.go, db/organizations.go
check the updated [api docs](https://github.com/vocdoni/saas-backend/blob/f/pending_org_invititations/api/docs.md#-list-pending-invitations).
=> feature: new endpoint for organization admins to get pending invitations

Dockerfile, api/users_test.go, cmd/service/main.go, notifications/mailtemplates/templates.go
using embedded folder to load html templates and protect available templates with a private variable and a getter to prevent sets
=> feature: use embedded folder to load html templates

api/organizations.go, db/types.go, stripe/stripe.go
=> Update stripe plan retrieval from procuts instead of price

api/docs.md, api/organizations.go
* return organization info when it is created
* api docs updated
=> feature: return org info on create

api/census.go, api/docs.md, api/types.go, db/census_membership.go
* Remove double response on add participants
* New struct to wrap census ID after creation
* API docs updated
=> Fix census endpoints bugs

.gemini/config.yaml, .gemini/styleguide.md
let's see if its PR reviews are useful
=> add gemini assistant config files

account/signature.go, api/api.go, api/api_test.go, api/apicommon/types.go, api/auth.go, api/auth_test.go, api/routes.go, cmd/service/main.go, docs/swagger.yaml, errors/errors_definition.go
More info in https://github.com/vocdoni/ui-scaffold/issues/864
=> feat(api): implements oauth login and register

api/api_test.go, api/transaction_test.go
=> feature: unit testing for tx faucet packages #19

db/census.go, db/census_membership.go, db/mongo.go, db/object.go, db/org_participants.go, db/organization_invites.go, db/organizations.go, db/plans.go, db/process.go, db/process_bundles.go, db/published_census.go, db/users.go, db/verifications.go
this is a small improvement addressing #69 
not yet tested deeply
=> db: use RLock in readonly ops

api/api.go, api/apicommon/types.go, api/census.go, api/census_test.go, api/docs.md, api/org_participants.go, api/org_participants_test.go, api/routes.go, db/org_participants.go, db/org_participants_test.go, docs/swagger.yaml
https://github.com/vocdoni/saas-backend/issues/100
=> Decouple Management of Organization vs Census Participants

api/api.go, api/apicommon/types.go, api/docs.md, api/organization_meta.go, api/organization_meta_test.go, api/routes.go, db/organizations.go, db/types.go, docs/swagger.yaml
=> Implements endoints for the meta Organization key/value store

api/api.go, api/apicommon/const.go, api/apicommon/types.go, api/docs.md, api/organization_meta.go, api/organizations.go, api/routes.go, assets/support.html, docs/swagger.yaml, notifications/mailtemplates/definitions.go, notifications/mailtemplates/templates.go, notifications/notifications.go, notifications/smtp/smtp.go
Relevant to https://github.com/vocdoni/saas-backend/issues/105
=> Adding email support endpoint

api/apicommon/types.go, api/docs.md, api/org_members.go, api/org_members_test.go, db/org_members.go, docs/swagger.yaml
=>  improve members crud

api/apicommon/types.go, api/docs.md, api/org_members.go, db/helpers.go, db/org_members.go, docs/swagger.yaml
=> api: members filtering

api/apicommon/types.go, api/stripe.go, csp/handlers/types.go, docs/swagger.yaml
this is a proposal to be evaluated / discussed
=> api: fix case issues (sessionID -> sessionId, etc)

db/org_members.go, db/org_members_groups.go, db/org_members_groups_test.go
the new test reproduces the original issue, here's the failure before the fix
=> db: fix ListOrganizationMemberGroup when pageSize==0
